---
# tasks file for hswong3i.nfs

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: hswong3i.nfs

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  notify: restart nfs
  tags: hswong3i.nfs

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/default/nfs-common.j2", dest: "/etc/default/nfs-common", owner: "root", group: "root", mode: "0644" }
    - { src: "etc/default/nfs-kernel-server.j2", dest: "/etc/default/nfs-kernel-server", owner: "root", group: "root", mode: "0644" }
  notify: restart nfs
  tags: hswong3i.nfs

- name: enable service
  service:
    name: "rpcbind"
    status: "enabled"
    enabled: "yes"
  notify: restart nfs
  tags: hswong3i.nfs

- name: enable service
  service:
    name: "nfs-kernel-server"
    enabled: "yes"
  notify: restart nfs
  tags: hswong3i.nfs
